// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { loadDotenv } from "./configs/loadDotenv";

loadDotenv();
import { defineConfig } from "prisma/config";
import { MIGRATIONS_DIR } from "./configs/db/databaseProvider";

/**
 * URL cho `prisma migrate deploy` (Vercel/Render build).
 * Thứ tự: PRISMA_DATABASE_URL → TURSO_DATABASE_URL (+ TURSO_AUTH_TOKEN) → DATABASE_URL.
 * Runtime app dùng `app/models/index.ts` + adapter theo URL (SQLite file / Turso / PostgreSQL).
 */
function datasourceUrlForPrismaMigrate(): string | undefined {
  const explicit = process.env["PRISMA_DATABASE_URL"]?.trim();
  if (explicit) return explicit;

  const token = process.env["TURSO_AUTH_TOKEN"]?.trim();
  const withTursoAuth = (url: string): string => {
    if (!url.startsWith("libsql:") || !token || url.includes("authToken=")) {
      return url;
    }
    const sep = url.includes("?") ? "&" : "?";
    return `${url}${sep}authToken=${encodeURIComponent(token)}`;
  };

  const turso = process.env["TURSO_DATABASE_URL"]?.trim();
  if (turso) return withTursoAuth(turso);

  const databaseUrl = process.env["DATABASE_URL"]?.trim();
  if (databaseUrl) return withTursoAuth(databaseUrl);

  return undefined;
}

export default defineConfig({
  schema: "app/models/schema.prisma",
  migrations: {
    path: MIGRATIONS_DIR,
  },
  datasource: {
    url: datasourceUrlForPrismaMigrate(),
  },
});
