service: irwin-framework-api
useDotenv: true # Cho phép load biến môi trường từ file .env

provider:
  name: aws
  runtime: nodejs20.x
  region: us-east-1 # Thay đổi theo region của anh
  environment:
    NODE_ENV: production
    DATABASE_URL: ${env:DATABASE_URL}

functions:
  api:
    handler: dist/lambda.handler

    events:
      - httpApi: "*"
  migrate:
    handler: dist/lambda.migrate # Handler chạy migration thủ công
    timeout: 300 # Cho phép chạy trong 5 phút

plugins:
  - serverless-offline

package:
  individually: true
  patterns:
    - "prisma/**" # Đảm bảo schema prisma được đóng gói để chạy migration
    - "!node_modules/.prisma/client/railsquery_engine-*" # Loại bỏ engine thừa để giảm dung lượng
    - "node_modules/.prisma/client/railsquery_engine-rhel-*" # Chỉ giữ lại engine cho Linux khi deploy
