import fs from "fs";
import path from "path";

const args = process.argv.slice(2);
if (args.length < 1) {
  console.error("Usage: yarn g:job Name");
  process.exit(1);
}

const name = args[0];
const root = process.cwd();
const jobName = `${name.charAt(0).toUpperCase() + name.slice(1).toLowerCase()}Job`;
const jobPath = path.join(root, "app/jobs", `${name.toLowerCase()}.job.ts`);

const template = `import { RailsJob } from "@rails";

/**
 * ${jobName} - Generated by irwin-framework
 */
export class ${jobName} extends RailsJob {
  async perform(data: any) {
    // TODO: Implement background logic
    console.log("Executing ${jobName} with data:", data);
  }
}
`;

const dir = path.dirname(jobPath);
if (!fs.existsSync(dir)) fs.mkdirSync(dir, { recursive: true });
fs.writeFileSync(jobPath, template);

console.log(`\x1b[32mCREATE\x1b[0m app/jobs/${name.toLowerCase()}.job.ts`);
console.log(`
\x1b[33mUsage:\x1b[0m
import { ${jobName} } from "@jobs/${name.toLowerCase()}.job";

// In your controller or service:
await ${jobName}.performLater({ user_id: 123 });
`);
