import fs from "fs";
import path from "path";

const args = process.argv.slice(2);
if (args.length < 2) {
  console.error("Usage: yarn g:concern [model|controller] Name");
  process.exit(1);
}

const type = args[0].toLowerCase(); // model or controller
const name = args[1];
const root = process.cwd();

const folder =
  type === "model" ? "app/models/concerns" : "app/controllers/concerns";
const fileName = `${name.toLowerCase()}.ts`;
const filePath = path.join(root, folder, fileName);

const template = `${type === "controller" ? 'import type { ApplicationController } from "../application.controller";\n\n' : ""}/**
 * ${name} Concern - Generated by irwin-framework
 */
export const ${name} = {
  // Define shared methods here
  async sharedMethod(${type === "controller" ? "this: ApplicationController" : ""}) {
    // logic
  }
};
`;

const dir = path.dirname(filePath);
if (!fs.existsSync(dir)) fs.mkdirSync(dir, { recursive: true });
fs.writeFileSync(filePath, template);

console.log(`\x1b[32mCREATE\x1b[0m ${path.relative(root, filePath)}`);
console.log(`
\x1b[33mUsage:\x1b[0m
import { ${name} } from "@${type}s/concerns/${name.toLowerCase()}";

// Then use it in your ${type}
`);
