import fs from "fs";
import path from "path";

const args = process.argv.slice(2);
if (args.length < 1) {
  console.error("Usage: yarn g:mailer Name [action action...]");
  process.exit(1);
}

const name = args[0];
const actions = args.slice(1);
const root = process.cwd();
const mailerPath = path.join(
  root,
  `app/mailers/${name.toLowerCase()}.mailer.ts`,
);

const template = `import { ApplicationMailer } from "./application.mailer";

/**
 * ${name}Mailer - Generated by irwin-framework
 */
export class ${name}Mailer extends ApplicationMailer {
${actions
  .map(
    (action) => `  static async ${action}(to: string, data: any) {
    await this.deliver({
      to,
      subject: "${action.replace(/_/g, " ")}",
      html: "<h1>Hello from Irwin Framework</h1>"
    });
  }`,
  )
  .join("\n\n")}
}
`;

const dir = path.dirname(mailerPath);
if (!fs.existsSync(dir)) fs.mkdirSync(dir, { recursive: true });
fs.writeFileSync(mailerPath, template);

console.log(
  `\x1b[32mCREATE\x1b[0m app/mailers/${name.toLowerCase()}.mailer.ts`,
);
console.log(`
\x1b[33mUsage:\x1b[0m
import { ${name}Mailer } from "@mailers/${name.toLowerCase()}.mailer";

// In your controller:
await ${name}Mailer.${actions[0] || "your_action"}("user@example.com", { some: "data" });
`);
