import fs from "fs";
import path from "path";

const args = process.argv.slice(2);
if (args.length < 1) {
  console.error("Usage: yarn g:service Name");
  process.exit(1);
}

const inputName = args[0];
const parts = inputName.split("/");
const rawName = parts.pop()!;
const subDir = parts.join("/").toLowerCase();

const serviceName = `${rawName.charAt(0).toUpperCase() + rawName.slice(1).toLowerCase()}Service`;
const root = process.cwd();
const serviceDir = path.join(root, "app/services", subDir);
const servicePath = path.join(
  serviceDir,
  `${rawName.toLowerCase()}.service.ts`,
);

const template = `/**
 * ${serviceName} - Generated by irwin-framework
 */
export class ${serviceName} {
  /**
   * Execute the service logic
   */
  async execute(params: any) {
    // TODO: Implement business logic
    return params;
  }
}
`;

const writeFile = (filePath: string, content: string) => {
  const dir = path.dirname(filePath);
  if (!fs.existsSync(dir)) fs.mkdirSync(dir, { recursive: true });
  fs.writeFileSync(filePath, content);
  console.log(`\x1b[32mCREATE\x1b[0m ${path.relative(root, filePath)}`);
};

writeFile(servicePath, template);

console.log(`
\x1b[33mUsage:\x1b[0m
import { ${serviceName} } from "@services/${subDir ? subDir + "/" : ""}${rawName.toLowerCase()}.service";

// In your controller:
const result = await new ${serviceName}().execute(this.req.body);
`);
