import fs from "fs";
import path from "path";

const args = process.argv.slice(2);
if (args.length < 1) {
  console.error("Usage: yarn g:factory ModelName");
  process.exit(1);
}

const modelName = args[0];
const root = process.cwd();
const factoryPath = path.join(
  root,
  "db/factories",
  `${modelName.toLowerCase()}.factory.ts`,
);

const template = `import { faker } from "@faker-js/faker";

/**
 * ${modelName} Factory - Generated by irwin-framework
 * Use this to generate mock data for tests or seeding.
 */
export const ${modelName}Factory = (overrides = {}) => {
  return {
    // TODO: Map your Prisma fields to faker methods
    // name: faker.person.fullName(),
    // email: faker.internet.email(),
    ...overrides
  };
};
`;

const dir = path.dirname(factoryPath);
if (!fs.existsSync(dir)) fs.mkdirSync(dir, { recursive: true });
fs.writeFileSync(factoryPath, template);

console.log(
  `\x1b[32mCREATE\x1b[0m db/factories/${modelName.toLowerCase()}.factory.ts`,
);
console.log(`
\x1b[33mUsage in tests:\x1b[0m
import { ${modelName}Factory } from "../../db/factories/${modelName.toLowerCase()}.factory";

const mockData = ${modelName}Factory({ email: "test@example.com" });
await models.${modelName.toLowerCase()}.create({ data: mockData });
`);
